APP_NAME = "KarCharcha"
USER_ID = "dev_user_01"
SESSION_ID = "pipeline_session_01"
GEMINI_MODEL = "gemini-2.0-flash" #"gemini-2.5-flash-preview-04-17"
INDIAN_LANG_CODES = ['en','hi','bn','gu','kn','ml','mr','od','pa','ta','te']
ALL_LANG_CODES = {
        "english": "en",
        "hindi": "hi",
        "tamil": "ta",
        "telugu": "te",
        "kannada": "kn",
        "malayalam": "ml",
        "marathi": "mr",
        "punjabi": "pa",
        "bengali": "bn",
        "gujarati": "gu",
        "odia": "or",
        "urdu": "ur",
        "assamese": "as",
        "maithili": "mai",
        "sanskrit": "sa",
        "sindhi": "sd",
        "nepali": "ne",
        "french": "fr",
        "german": "de",
        "greek": "el",
        "gujarati": "gu",
        "japanese": "ja",
        "korean": "ko",
        "marathi": "mr",
        "russian": "ru",
        "tamil": "ta",
        "telugu": "te",
        "urdu": "ur",
        "vietnamese": "vi",
        "chinese": "zh",
        "hindi": "hi",
        "bengali": "bn",
        "gujarati": "gu",
        "kannada": "kn",
        "malayalam": "ml",
        "marathi": "mr",
        "odia": "or",
        "punjabi": "pa",
        "tamil": "ta",
        "telugu": "te",
        "urdu": "ur"
    }